//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotdeFumar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotdeFumar.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAYAAACLz2ctAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMjHxIGmVAACeaklEQVR4Xu39BZQU1/r9D98oIUBwd3d3d4dh0AEGGNzd3QZ3J0iUuJGEKHEhHoi74TIwLu373ftU19A0RUJyb/L9rf+bXmtT3aere4auz+xHzqnq/wD4V//q/0yOg//qX/1Tchz8V//qn5Lj4L/6V/+UHAf/1b/6p+Q4+K/+1T8lx8F/9a/+KTkO/qt/9U/JcfBf/at/So6D/+pf/VNyHHSUdv3bdKOzbr5e3eKga41fvwLlywMTJwLPPgt88cW19f0PQHw8PybevF7gxx+B/fuAdu0c3/dKhf9frkPm8wn/3MI/0/9j8d/rkeOgo8J/wH+t0A+N90M+4EDVKggMHgwsWABs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mariRage1 {
            get {
                return ResourceManager.GetString("mariRage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMjHxIGmVAABoSElEQVR4Xu29B5Qc5Zk1PDnnnHPOOXZP6JmenHPOI2lGOSMUQVkajcIoCxAICYHIJhlswAbjtF7v2mtv/ne9a3vtzxHbZJDuf5/q7pluMeAWsF6fA++ce6re6uqqmrr3SW+FtgDwBT7HWHThF/j8YNGFX+Dzg0UXfoHPDxZd+AU+P1h04Rf4/GDRhV/g84NFF/45fAbNinAg/Ny8nbu8Atxe8PR1+4OVtZVsXA9L2NjY3CBgZWW83BQ29rZvuLi5vMJ1drKfQNgQn6ZZEj7c77S1tc03rK2tf2llaf0Gl83v09LC8o/WNra/5ee/M1r+FSKdkP9LtvFX20y4NO6Yi0/R5MQE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monkaGun {
            get {
                return ResourceManager.GetString("monkaGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB0CAYAAABNPTrEAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwwAADsMBx2+oZAAAABl0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4yMfEgaZUAADiMSURBVHhe7X0HfFRV2j4lJCEhAdJ7771P6kwmvYcOoQcINQnFgiAqCDYsKIgoFkTsfW3b19399FvdXXe/FV1d3f+urhUQEQtSMvP83+fcucMQBwWBCG5Ofs/vTm45571vf89tA/pbf+tv/a2/9bf+1t/6W3/rb/2tv31LG2hb9rf/0kYF+L7obyfYdIYNOg4cmarjTDb2z3HZ9N8nC0daif7m0ByZxNabWcfD0Qb5n9D6GWxbno7mKDw2P0GeoFrQJpgmmNoLXDdJUCMoF2QIAgSkS+9Lp/W/suknP9gmNDZ96SkIF+QKjIKyXigVJAuiBaGC4QIPgWM/jr/JdF0h9PUn0ri/LiBfwRRXz8Hbg+K8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string smoker {
            get {
                return ResourceManager.GetString("smoker", resourceCulture);
            }
        }
    }
}
